use wheel 0.43.0 as 0.44.0 breaks package build
```
$ pip3 install /home/sam/Downloads/python-sdks/
Processing /home/sam/Downloads/python-sdks
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/anybotics/projects/anybotics/inspection_ws/catkin_ws/build/anymal_livekit_environment/venv3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/anybotics/projects/anybotics/inspection_ws/catkin_ws/build/anymal_livekit_environment/venv3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/anybotics/projects/anybotics/inspection_ws/catkin_ws/build/anymal_livekit_environment/venv3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-mxlyekqe/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-mxlyekqe/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-mxlyekqe/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ImportError: cannot import name 'get_platform' from 'wheel.bdist_wheel' (/tmp/pip-build-env-mxlyekqe/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```